# The text-command matrix: one row per sentence (gen_matrix.py, make_clips.py read it).
# (id, feature, thai_text, expected_route, expected_action_type, expected_reply_gist,
#  SAFE, how_to_test_safely, speakable, key_part)
TEST_ALARM_NOTE = ("label is ทดสอบ: send TEST_ALARM_CLEAR right after (removes every alarm named "
                   "ทดสอบ); the time is hours away so it cannot ring first")
CAL_CANCEL = ("the confirm step is the guard: when Jarvis says 'จะลงนัด ... พูดว่า ยืนยัน' send D90 "
              "'ยกเลิก' (never 'ยืนยัน'); without a live grant it first asks for the identity check - "
              "back out of it (no screenshot of the face camera)")
LIGHTS_OFF = ("Poom runs `python -m kiosk_broker ewelink-control off` ON THE VPS first (every switch "
              "refused: reply 'ตอนนี้ปิดการสั่งไฟไว้ครับ'), then `ewelink-control on` after; if Jarvis asks "
              "back ('...อยู่แล้ว ต้องการ...ใช่ไหม' / 'ดวงไหน') answer 'ยกเลิก'. Or offline only")
NOTE_UNDO = ("adds one line to the phone's own list: open หน้าโน้ต in the Control Panel afterwards and "
             "take the line out (no identity check needed); or send the same sentence with the item "
             "'ทดสอบ'")
LEAVES = "opens another app over the kiosk; send TEST_HOME right after (or offline only)"

ROWS = [
    # ---- camera (actions.camera_match) -------------------------------------------------
    ("C01", "camera", "ขอดูกล้องหน่อยครับ", "code:camera", "open_camera_app", "กำลังเปิดกล้องให้ครับ",
     "NO", LEAVES, "yes", "กล้อง"),
    ("C02", "camera", "เปิดกล้องหน่อย", "code:camera", "open_camera_app", "กำลังเปิดกล้องให้ครับ",
     "NO", LEAVES, "yes", "กล้อง"),
    ("C03", "camera", "กล้องวงจรปิดยี่ห้อไหนดี", "model", "none", "advice about CCTV brands (question-word)",
     "yes", "", "yes", "กล้องวงจรปิด"),
    ("C04", "camera", "ขอดูกล่องหน่อย", "model", "none", "model answer (near-miss:กล่อง is logged, not matched)",
     "yes", "", "no", "กล่อง"),
    # ---- alarms (alarms.alarm_match) ---------------------------------------------------
    ("A01", "alarm", "ตั้งปลุกตีสาม ชื่อทดสอบ", "code:alarm", "set_alarm", "ตั้งปลุก ตี 3 ชื่อทดสอบ แล้วครับ",
     "NO", TEST_ALARM_NOTE, "yes", "ตีสาม"),
    ("A02", "alarm", "ตั้งปลุก 11 โมงเช้า ชื่อทดสอบ ได้ไหมครับ", "code:alarm", "set_alarm",
     "ตั้งปลุก 11 โมงเช้า ชื่อทดสอบ แล้วครับ", "NO", TEST_ALARM_NOTE, "yes", "11 โมงเช้า"),
    ("A03", "alarm", "ปลุกหกโมงครึ่ง ไปทำงาน", "code:alarm", "set_alarm", "ตั้งปลุก 6 โมงเช้าครึ่ง ชื่อไปทำงาน แล้วครับ",
     "NO", "label is not ทดสอบ so TEST_ALARM_CLEAR will not remove it: offline only, or delete it by hand "
     "on the alarm screen", "yes", "หกโมงครึ่ง"),
    ("A04", "alarm", "ตั้งปลุกห้าทุ่มครึ่ง ชื่อทดสอบ", "code:alarm", "set_alarm", "ตั้งปลุก 5 ทุ่มครึ่ง ชื่อทดสอบ แล้วครับ",
     "NO", TEST_ALARM_NOTE + " (run before 23:00)", "yes", "ห้าทุ่มครึ่ง"),
    ("A05", "alarm", "ตั้งปลุกสองโมง", "code:alarm", "none", "asked back: 2 โมงเช้าหรือบ่าย 2 โมง (nothing set)",
     "yes", "", "yes", "สองโมง"),
    ("A06", "alarm", "ตั้งปลูก 11 โมงเช้า ชื่อทดสอบ", "code:alarm", "set_alarm",
     "ตั้งปลุก 11 โมงเช้า ชื่อทดสอบ แล้วครับ (misheard ปลูก read as ปลุก)", "NO", TEST_ALARM_NOTE, "no", "ปลูก"),
    ("A07", "alarm", "ปิดปลุกทดสอบ", "code:alarm", "alarm_enable", "ปิดปลุก ทดสอบ แล้วครับ",
     "yes", "touches only alarms named ทดสอบ; run after A01 and before TEST_ALARM_CLEAR", "yes", "ปิดปลุก!เปิดปลุก|ทดสอบ"),
    ("A08", "alarm", "ปิดปลุกทั้งหมด", "code:alarm", "alarm_enable", "ปิดปลุก ทั้งหมด แล้วครับ",
     "NO", "switches off Poom's REAL alarms: offline only (or note which were on and switch them back "
     "on the alarm screen)", "yes", "ปิดปลุก!เปิดปลุก|ทั้งหมด"),
    ("A09", "alarm", "ตั้งปลุกยังไง", "model", "none", "explains how (question:ยังไง)", "yes", "", "yes", "ยังไง"),
    ("A10", "alarm", "ปลูกต้นไม้ตอนไหนดี", "model", "none", "gardening answer (planting, not ปลุก)",
     "yes", "", "yes", "ปลูกต้นไม้"),
    # ---- calendar read (calendar_read.calendar_match) ----------------------------------
    ("K01", "calendar_read", "วันนี้มีนัดอะไรบ้าง", "code:calendar_read", "verify_identity",
     "no grant: ขอยืนยันตัวตนก่อน; with a grant: today's/tomorrow's appointments", "yes",
     "read only; opens the identity check - no screenshot while the face camera is on", "yes", "นัด"),
    ("K02", "calendar_read", "พรุ่งนี้มีประชุมไหม", "code:calendar_read", "verify_identity",
     "as K01", "yes", "as K01", "yes", "ประชุม"),
    ("K03", "calendar_read", "วันนี้มีนักอะไรบ้าง", "code:calendar_read", "verify_identity",
     "as K01 (misheard นัก accepted in the question's shape)", "yes", "as K01", "no", "นัก"),
    ("K04", "calendar_read", "นักเรียนเข้าเรียนกี่โมง", "model", "none", "ordinary answer (near-miss:นัก)",
     "yes", "", "yes", "นักเรียน"),
    # ---- calendar add (calendar_add.match) ---------------------------------------------
    ("D01", "calendar_add", "ลงนัดพรุ่งนี้บ่ายสองไปหาหมอฟัน", "code:calendar_add", "verify_identity",
     "no grant: identity first; then 'จะลงนัด พรุ่งนี้ (...) บ่าย 2 โมง ไปหาหมอฟัน ถ้าถูกต้องพูดว่า ยืนยัน'",
     "NO", CAL_CANCEL, "yes", "บ่ายสอง|หาหมอฟัน"),
    ("D02", "calendar_add", "เพิ่มนัดวันศุกร์หน้า สิบโมง ประชุมทีม", "code:calendar_add", "verify_identity",
     "as D01, วันศุกร์หน้า 10 โมง ประชุมทีม", "NO", CAL_CANCEL, "yes", "ศุกร์หน้า|สิบโมง|ประชุมทีม"),
    ("D03", "calendar_add", "ลงนัดพรุ่งนี้ไปหาหมอ", "code:calendar_add", "none",
     "asked back: นัดกี่โมงครับ (nothing held, no grant needed)", "yes", "", "yes", "ลงนัด"),
    ("D04", "calendar_add", "ลงนัดสองโมง ตัดผม", "code:calendar_add", "none",
     "asked back: 2 โมงเช้าหรือบ่าย 2 โมง (nothing held)", "yes", "", "yes", "สองโมง"),
    ("D05", "calendar_add", "ลงนัดยังไง", "model", "none", "explains (question:ยังไง)", "yes", "", "yes", "ลงนัด"),
    ("D90", "calendar_add", "ยกเลิก", "code:calendar_add (only while a draft is held)", "none",
     "ยกเลิกแล้ว ไม่ได้ลงนัดครับ; with nothing held it is an ordinary sentence (model)", "yes",
     "the cancel step for D01/D02", "yes", "ยกเลิก"),
    ("D91", "calendar_add", "ยืนยัน", "model (no draft held)", "none",
     "with nothing held: ordinary; within 10 min of an expired draft: หมดเวลายืนยัน", "yes",
     "never send it while D01/D02's draft is held", "no", "ยืนยัน"),
    # ---- notes / shopping list (notes.notes_match) -------------------------------------
    ("N01", "notes", "เพิ่ม นม ในรายการซื้อของ", "code:notes", "note_add", "เพิ่ม นม ในรายการซื้อของแล้วครับ",
     "NO", NOTE_UNDO, "yes", "นม"),
    ("N02", "notes", "จดว่าซื้อไข่", "code:notes", "note_add", "เพิ่ม ไข่ ในรายการซื้อของแล้วครับ",
     "NO", NOTE_UNDO, "yes", "ไข่"),
    ("N03", "notes", "ซื้อ น้ำปลา ด้วย", "code:notes", "note_add", "เพิ่ม น้ำปลา ในรายการซื้อของแล้วครับ",
     "NO", NOTE_UNDO, "yes", "น้ำปลา"),
    ("N04", "notes", "จดว่าพรุ่งนี้ต้องจ่ายค่าไฟ", "code:notes", "note_add", "จดไว้ในโน้ตแล้วครับ",
     "NO", NOTE_UNDO, "yes", "จ่ายค่าไฟ"),
    ("N05", "notes", "อ่านรายการซื้อของ", "code:notes", "note_read", "the phone reads its own shopping list",
     "yes", "", "yes", "รายการซื้อของ"),
    ("N06", "notes", "ต้องซื้ออะไรบ้าง", "code:notes", "note_read", "as N05", "yes", "", "yes", "ซื้อ"),
    ("N07", "notes", "ในรายการซื้อของมีนมไหม", "code:notes", "note_read", "as N05 (read:question)",
     "yes", "", "yes", "รายการซื้อของ"),
    ("N08", "notes", "ลบนมออกจากรายการซื้อของ", "code:notes", "none",
     "ลบหรือขีดรายการด้วยเสียงยังทำไม่ได้ครับ ... (nothing removed)", "yes", "", "yes", "ลบ"),
    ("N09", "notes", "อ่านโน้ต", "code:notes", "note_read", "the phone reads its notes list", "yes", "", "yes", "โน้ต"),
    ("N10", "notes", "ซื้ออะไรดี", "model", "none", "ordinary answer (question)", "yes", "", "yes", "ซื้อ"),
    # ---- lights (lights.handle; offline: lights.parse only) ----------------------------
    ("L01", "lights", "เปิดไฟห้องนั่งเล่น", "code:lights", "home_updated", "what eWeLink did: เปิด...แล้วครับ / offline / not allowed",
     "NO", LIGHTS_OFF, "yes", "เปิดไฟ|ห้องนั่งเล่น"),
    ("L02", "lights", "ปิดไฟหน้าบ้าน", "code:lights", "home_updated", "as L01", "NO", LIGHTS_OFF, "yes", "ปิดไฟ!เปิดไฟ|หน้าบ้าน"),
    ("L03", "lights", "ปิดไฟทั้งหมด", "code:lights", "home_updated", "as L01, every allowlisted light", "NO",
     LIGHTS_OFF, "yes", "ปิดไฟ!เปิดไฟ|ทั้งหมด"),
    ("L04", "lights", "ไฟห้องนอนเปิดอยู่ไหม", "code:lights", "none", "the state read fresh from eWeLink (question, never a switch)",
     "yes", "", "yes", "ไฟห้องนอน"),
    ("L05", "lights", "เปิดไฟห้องใต้ดิน", "code:lights", "none",
     "ไม่พบไฟชื่อนั้น OR asked back 'ดวงไหน' - but with ONE light in the house the only-one rule SWITCHES it",
     "NO", LIGHTS_OFF + ". A made-up name is NOT safe by itself (only-one rule)", "yes", "ห้องใต้ดิน"),
    ("L06", "lights", "เปิดไฟแล้วก็ปิดไฟ", "code:lights", "none", "กรุณาสั่งเปิดหรือปิดทีละอย่างครับ (both verbs)",
     "yes", "", "yes", "เปิดไฟ|ปิดไฟ"),
    ("L07", "lights", "อย่าเปิดไฟนะ", "model", "none", "ordinary answer (negated: not a command); a claimed switch is replaced",
     "yes", "", "yes", "อย่า"),
    # ---- music (music.match; the phone: media/MusicVoice) ------------------------------
    ("M01", "music", "เปิดเพลงของบอดี้สแลม", "code:music", "music", "เปิดเพลง บอดี้สแลม ครับ / ไม่พบเพลง \"บอดี้สแลม\" ใน playlist ครับ",
     "yes", "plays a song if found; stop with M05", "yes", "บอดี้สแลม"),
    ("M02", "music", "เปิดเพลงคิดถึง", "code:music", "music", "as M01, query คิดถึง", "yes", "stop with M05", "yes", "คิดถึง"),
    ("M03", "music", "เปิดเพลงฝนตกที่ดาวอังคาร", "code:music", "music", "ไม่พบเพลง \"ฝนตกที่ดาวอังคาร\" ใน playlist ครับ (a not-found search)",
     "yes", "", "yes", "ฝนตกที่ดาวอังคาร"),
    ("M04", "music", "หยุดเพลง", "code:music", "music", "หยุดเพลงชั่วคราวครับ / ตอนนี้ไม่มีเพลงเล่นอยู่ครับ", "yes", "", "yes", "หยุดเพลง"),
    ("M05", "music", "ปิดเพลง", "code:music", "music", "ปิดเพลงแล้วครับ", "yes", "", "yes", "ปิดเพลง!เปิดเพลง"),
    ("M06", "music", "เพลงถัดไป", "code:music", "music", "เพลงถัดไปครับ", "yes", "", "yes", "ถัดไป"),
    ("M07", "music", "เพลงก่อนหน้า", "code:music", "music", "ย้อนไปเพลงก่อนหน้าครับ", "yes", "", "yes", "ก่อนหน้า"),
    ("M08", "music", "เล่นเพลงต่อ", "code:music", "music", "เล่นเพลงต่อครับ", "yes", "", "yes", "เล่นเพลงต่อ"),
    ("M09", "music", "เพิ่มเสียงเพลง", "code:music", "music", "เพิ่มเสียงเพลงครับ", "yes",
     "moves the player volume one step: undo with M10", "yes", "เพิ่มเสียง"),
    ("M10", "music", "ลดเสียงเพลง", "code:music", "music", "ลดเสียงเพลงครับ", "yes", "", "yes", "ลดเสียง"),
    ("M11", "music", "เพลงนี้ชื่ออะไร", "model", "none", "ordinary answer (question)", "yes", "", "yes", "ชื่ออะไร"),
    ("M12", "music", "เปิดเพรงของคาราบาว", "code:music", "music", "as M01, query คาราบาว (misheard เพรง)",
     "yes", "stop with M05", "no", "คาราบาว"),
    ("M13", "music", "เปิดเพลงคาราบาว", "code:music", "music", "as M01, query คาราบาว", "yes", "stop with M05", "yes", "คาราบาว"),
    # ---- video (video.match; the phone: media/VideoVoice) ------------------------------
    ("V01", "video", "เปิดวิดีโอ", "code:video", "video", "the one left paused, or จะดูวิดีโอเรื่องไหนครับ", "yes",
     "stop with V04", "yes", "วิดีโอ"),
    ("V02", "video", "เปิดวิดีโอเรื่องเที่ยวเชียงราย", "code:video", "video",
     "เปิดวิดีโอ เที่ยวเชียงราย ครับ / ไม่พบวิดีโอ ... ใน playlist ครับ", "yes", "stop with V04", "yes", "เที่ยวเชียงราย"),
    ("V03", "video", "หยุดวิดีโอ", "code:video", "video", "หยุดวิดีโอชั่วคราวครับ / วิดีโอหยุดอยู่แล้วครับ", "yes", "", "yes", "หยุดวิดีโอ"),
    ("V04", "video", "ปิดวิดีโอ", "code:video", "video", "ปิดวิดีโอแล้วครับ", "yes", "", "yes", "ปิดวิดีโอ!เปิดวิดีโอ"),
    ("V05", "video", "ดูวิดีโอต่อ", "code:video", "video", "เล่นวิดีโอต่อครับ / ไม่มีวิดีโอที่ค้างไว้ครับ", "yes",
     "stop with V04", "yes", "วิดีโอต่อ"),
    ("V06", "video", "เปิดคลิปแมว", "code:video", "video", "as V02, query แมว", "yes", "stop with V04", "yes", "แมว"),
    # ---- maps (the model, open_maps; speech_gate.has_maps_word adds the area line) ------
    ("P01", "maps", "พาไปเซ็นทรัลเชียงราย", "model", "open_maps", "กำลังเปิดแผนที่ไปเซ็นทรัลเชียงราย + Maps opens",
     "NO", LEAVES + "; costs one model call", "yes", "เซ็นทรัล"),
    ("P02", "maps", "พาไปภูชี้ฟ้าเชียงราย", "model", "open_maps", "as P01, ภูชี้ฟ้า", "NO", LEAVES, "yes", "ภูชี้ฟ้า"),
    ("P03", "maps", "นำทางไปวัดร่องขุ่น", "model", "open_maps", "as P01, วัดร่องขุ่น", "NO", LEAVES, "yes", "ร่องขุ่น"),
    ("P04", "maps", "เปิดแผนที่ไปสิงห์ปาร์ค", "model", "open_maps", "as P01, สิงห์ปาร์ค", "NO", LEAVES, "yes", "สิงห์ปาร์ค"),
    ("P05", "maps", "ไปดอยตุงยังไง", "model", "none or open_maps", "directions talk; no map word, so the model decides; local fact ดอยตุง added",
     "NO", LEAVES + " (if the model chooses the map)", "yes", "ดอยตุง"),
    # ---- weather, forecast, clock, gold, oil, local facts (the model, with prompt lines) --
    ("W01", "weather", "วันนี้อากาศเป็นยังไง", "model", "none", "from the weather line (the screen's own weather)", "yes", "", "yes", "อากาศ"),
    ("W02", "forecast", "พรุ่งนี้ฝนจะตกไหม", "model", "none", "from the forecast detail line", "yes", "", "yes", "ฝน"),
    ("W03", "forecast", "วันนี้ฝุ่นเยอะไหม", "model", "none", "from the forecast detail line (ฝุ่น/PM)", "yes", "", "yes", "ฝุ่น"),
    ("T01", "clock", "ตอนนี้กี่โมงแล้ว", "model", "none", "the Thai clock from the context line", "yes", "", "yes", "กี่โมง"),
    ("T02", "clock", "วันนี้วันที่เท่าไหร่", "model", "none", "the Thai date from the context line", "yes", "", "yes", "วันที่"),
    ("G01", "gold", "ราคาทองวันนี้เท่าไหร่", "model", "none",
     "gold is NOT in the prompt (dashboard only): should say it cannot see it / look at the card - must not invent a number",
     "yes", "", "yes", "ราคาทอง"),
    ("O01", "oil", "น้ำมันดีเซลวันนี้ลิตรละเท่าไหร่", "model", "none", "from the oil line (cached dashboard)", "yes", "", "yes", "ดีเซล"),
    ("F01", "local_facts", "แม่ฟ้าหลวงเป็นมหาลัยรัฐหรือเอกชน", "model", "none",
     "มหาวิทยาลัยของรัฐในกำกับของรัฐ (checked fact line)", "yes", "", "yes", "แม่ฟ้าหลวง"),
    # ---- features with NO voice command (must go to the model and claim nothing) -------
    ("X01", "no-voice:radio", "เปิดวิทยุ", "model", "none",
     "must not claim the radio is on; e.g. open วิทยุ from the Control Panel", "yes", "", "yes", "วิทยุ"),
    ("X02", "no-voice:timer", "จับเวลาห้านาที", "model", "none",
     "must not claim a timer was set (no timer action exists)", "yes", "", "yes", "ห้านาที"),
    ("X03", "no-voice:flashlight", "เปิดไฟฉาย", "model", "none",
     "flashlight has no voice command - but 'ไฟ' makes it a LIGHTS sentence (see offline column)",
     "NO", LIGHTS_OFF, "yes", "ไฟฉาย"),
    ("X04", "no-voice:recorder", "อัดเสียงให้หน่อย", "model", "none", "must not claim recording started", "yes", "", "yes", "อัดเสียง"),
    ("X05", "no-voice:calculator", "สามร้อยคูณสิบสองได้เท่าไหร่", "model", "none", "3600", "yes", "", "yes", "สามร้อย"),
    # ---- conversation ------------------------------------------------------------------
    ("Q01", "chat", "สวัสดีจาร์วิส", "model", "none", "a short greeting", "yes", "", "yes", "สวัสดี"),
    ("Q02", "chat", "เล่านิทานสั้นๆให้ฟังหน่อย", "model", "none", "a short story (≤70 chars)", "yes", "", "yes", "นิทาน"),
]
